### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by adhawkins** [kalekundert/pytest_tmp_files#3]
Hi,

I'm trying to package this up for Alpine, and am having trouble getting it to run the tests. It doesn't seem to be able to find the fixture `tmp_files`:

```
file /tmp/pytest-of-builder/pytest-0/test_tmp_files_indirect0/test_tmp_files_indirect.py, line 3
  @pytest.mark.parametrize(
          'tmp_files, expected', [
                  ({'file.txt': 'spam'}, 'spam'),
                  ({'file.txt': 'eggs'}, 'not eggs'),
          ],
          indirect=['tmp_files'],
  )
  def test_open(tmp_files, expected):
E       fixture 'tmp_files' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

The command I'm running is:

`PYTHONPATH="$PWD" pytest tests/`

I've tried creating a `conftest.py` containing:

```
from pytest_tmp_files import plugin
```

But this doesn't help.

Suggestions appreciated!

**Comment by kalekundert** [comment]
Usually this error means that `pytest_tmp_files` isn't installed.  It shouldn't be necessary to import anything.  If you're curious how pytest finds the `tmp_files` fixture, it's via the [`pytest11` entry point](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html#setuptools-entry-points) (defined in `pyproject.toml`).

**Comment by adhawkins** [comment]
That's the point, I want to run the tests at the package creation point. The package isn't installed yet

**Comment by kalekundert** [comment]
Hmmm...  The package has to be registered as a pytest plugin for the tests to run.  I don't know anything about packaging, but I'm surprised there's not a way to deal with this.  Surely there must be lots of packages that have to be installed before they can be tested, right?

In any case, it looks like you might be able to set the `$PYTEST_PLUGINS` environment variable to get pytest to treat the source code as a plugin, see [here](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html#plugin-discovery-order-at-tool-startup) and [here](https://docs.pytest.org/en/7.1.x/reference/reference.html#envvar-PYTEST_PLUGINS).  You could also always (i) create a virtual environment, (ii) install the package in there, (iii) run the tests, then (iv) delete the virtual environment.  Your `conftest.py` idea was good, but I think it didn't work because these tests spawn fresh pytest processes, so anything imported in the parent process isn't seen by its children.

Let me know if any of those ideas help.

**Comment by adhawkins** [comment]
The venv idea was the key. I realised that alpine packages up other pytest fixtures, and when I looked at how they are tested, they use the venv approach.

I've duplicated that in this package, and it now tests Ok.

Thanks for the assistance. Much appreciated.

**Comment by kalekundert** [comment]
No problem, glad you got it working!
